spring:
  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/micro-sale?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://cloudy:cloudy@${EUREKA_HOST:localhost}:${EUREKA_PORT:8812}/eureka/
server:
  port: 8806
mybatis:
  type-aliases-package: com.hechihan.micro.apps.sale.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #全局缓存
    cache-enabled: true
    # 延迟加载
    lazy-loading-enabled: true
    # 允许 JDBC 支持自动生成主键
    use-generated-keys: true


logging:
  level:
    com.hechihan.micro.apps.sale.mapper: debug
flyway:
  enabled: true
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  check-location: true
  locations: classpath:db/migration
  validate-on-migrate: true
  clean-on-validation-error: true
#  target: 1.1.0.2
  baseline-on-migrate: true
  baseline-version: 1.0
  baseline-description: base
